# Generated by Django 4.2.7 on 2024-12-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="hackathon",
        ),
        migrations.AddField(
            model_name="project",
            name="hackathons",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="hackathon.hackathon"
            ),
        ),
    ]
