# Generated by Django 4.2.7 on 2024-12-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0002_remove_project_hackathon_project_hackathons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="hackathons",
        ),
    ]
